config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get '/home', to: 'pages#home'

  # get '/recipes', to: 'recipes#index'
  # get '/recipes/new', to: 'recipes#new', as: 'new_recipe'
  # post '/recipes', to: 'recipes#create'

  # get '/recipes/:id/edit', to: 'recipes#edit', as: 'edit_recipe'
  # patch '/recipes/:id', to: 'recipes#update'
  # get '/recipes/:id', to: 'recipes#show', as: 'recipe'
  # delete '/recipes/:id', to: 'recipes#destroy'

  resources :recipes do
    member do
      post 'like'
    end
  end

  resources :chefs, except: [:new, :destroy]

  get '/register', to: 'chefs#new'

  get '/login', to: "logins#new"
  post '/login', to: "logins#create"
  get '/logout', to: "logins#destroy"

  resources :styles, only: [:new, :create, :show]
  resources :ingredients, only: [:new, :create, :show]
  end

app/views/pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to MyRecipe APP</h1>
  <h2>This is the home page for MyRecipe Application</h2>
  <%= link_to "Sign up now!", register_path, class:"btn btn-lg btn-success"%>
</div>

<div id="recipedivcontainer"style="">
  <div id="innerrecipediv" style="">
    <h3 class="left">
      View Recipe as Guest User
    </h3>
    <h2 class="left">
      Browse Recipe as Guest!!
    </h2>
    <p><%= link_to "Browse Recipe Listings", recipes_path, class:"btn btn-warning btn-small" %></p>
  </div>
  <div id="dividerdivblock"style="">
    <p id="dividerline"></p>
  </div>
  <div id="innerrecipediv" style="">
    <h3 class="left">
      Sign in to your account
    </h3>
    <h2 class="left">
      Operate Your Recipes !!!!!
    </h2>
    <p><%= link_to "Login to your acc", login_path, class:"btn btn-warning btn-small" %></p>
  </div>
  <div id="dividerdivblock" style="">
    <p id="dividerline"></p>
  </div>
  <div id="innerrecipediv" style="">
    <h3 class="left">
      View Recipe as Guest User
    </h3>
    <h2 class="left">
      Browse Recipe as Guest!!
    </h2>
    <p><%= link_to "Browse Recipe Listings", "", class:"btn btn-warning btn-small" %></p>
  </div>
</div>





<!-- <div id="divblocksize">
  <div style="width:30%; margin-left:0px;" class="col-lg-4">
    <h3 class="midrow">
      View Recipe as Guest User
    </h3>
    <h2 class="left">
      Browse and View Recipe as Guest!!!!!!!
    </h2>
    <p><%= link_to "Browse Recipe Listings", "", class:"btn btn-warning btn-small" %></p>
  </div>
  <div id="dividerdiv" class="col-lg-4">
    <p id="dividerline" class="midrow"></p>
  </div>
  <div id="browserecipestyle" class="col-lg-4">
    <h3 class="midrow">
      View Recipe as Guest User
    </h3>
    <h2 class="left">
      Browse and View Recipe as Guest!!!!!!!
    </h2>
    <p><%= link_to "Browse Recipe Listings", "", class:"btn btn-warning btn-small" %></p>
  </div>
  <div id="dividerdiv" class="col-lg-4">
    <p id="dividerline" class="midrow"></p>
  </div>
  <div id="browserecipestyle" class="col-lg-4">
    <h3 class="midrow">
      View Recipe as Guest User
    </h3>
    <h2 class="left">
      Browse and View Recipe as Guest!!!!!!!
    </h2>
    <p><%= link_to "Browse Recipe Listings", "", class:"btn btn-warning btn-small" %></p>
  </div>
</div> -->